import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Opportunity } from '../models/opportunity';

@Injectable({
  providedIn: 'root'
})
export class OpportunityService {

  private opportunities: Opportunity[] = [
    {
      id: 1,
      title: "Master's Excellence Scholarship 2024",
      type: 'Scholarship',
      organization: 'University of Toronto',
      orgDescription: 'Leading public research university in Toronto.',
      location: 'Toronto, Canada',
      updatedAt: '2 days ago',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzVdf5pEShN21PMJh5FgtmbWFyMxG745kiY1O9iAmH-sJDd6Xwo096ZkdD3HxUBUjmyrOnDHINSjZyqyic-QI5zSDNbrIeb8cLmoWWxpzPfGYQGlEGwj0DOuHALekHTDM76kO4FC-3yTXRY-55lvBdDkwRvTvAVXhWjjsVXYvNAinaDG77OfZ9p-h3vlKKaHf-0ZriNQej2ytxUsiyztcytZefeTxEAMwAEKJwhpUfg0Ju1UoyrMQXaKSPij0IBjrfmAAjAcqX2WQ',
      logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-xI8JqdpaSSNYcdKGLV5oy1XcpyVjOD-yfqiXRzUwdVPqd_pvGR_bZodg_sfN6sijcW-Ix_fpFPM46OUY_Z_SVh5eXTq95snVnR6kXiZ4cQGG6mrod7Epvvml7PVDygGG24et6u2w-Lmy4sOAVSiV-NMZAVSIgqDSRsts5jb_6rJF0DSb1Eg-5bd0dCbP9uUA53zS1WgCzyWM8fEvTcQSEgDoORQFk_7ue2sJ4adxjj4wlXgUt5sq067Id0mrvOmpjdUvPdSgzHY',
      description: "Prestigious award for high-achieving Engineering students to pursue graduate studies.",
      benefits: "Full tuition coverage.",
      level: "Master's Degree",
      eligibility: ["International student", "Engineering background"],
      deadline: "Oct 15, 2024",
      value: "$35,000 / year",
      duration: "2 Years",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 2,
      title: "International Student Fair",
      type: 'Event',
      organization: 'Global Education',
      orgDescription: 'Event description.',
      location: 'London, UK',
      updatedAt: '1 week ago',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQGIiIYiYJrUnTffhyBs8YhtFTiYVwWEzV3VkD_hLUwF-V-Z_Ax8oIUCjdkQZ37A6GIslYMNnizE_cprTemFgn8j0SA_f8EVQPA8YSdRdtIl65Q4nVpuJURPWOof6XuGmAWj9XVrJfnUZmFMqruB5MFY7HbvA0CJI8aO1GHlz8kO2t1P6p0WiGrKIyZUGuySIbbjsjkfdfwVVk8cYBekjkkiS2elzOPedc_VtSQtEkCWg2Eend8VL_eJpw8TrK6vLcf5HY855kGxw',
      logoUrl: 'https://t3.ftcdn.net/jpg/04/91/76/62/360_F_491766294_h4j7LbW2YgfbNHhq7F8GboIc1XyBSEY5.jpg',
      description: "Meet representatives.",
      benefits: "Free entry",
      eligibility: ["All"],
      deadline: "Nov 12, 2024",
      value: "Free",
      duration: "1 Day",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 203,
      title: "Intro to Data Analytics",
      type: "Training",
      organization: "Global Data Hub",
      orgDescription: "Data School",
      location: "Online",
      updatedAt: "3 days ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAzvkX5lwHBFrDZ-vOXEHyI20EeMu2q6kMA-6NPzzgj17HYyPOhSAY3gv_uTwFRNiZk1hzJWfNy-IlvPl1ZFzAx1Lm3TeKI81t7NBhAvC_DDOLR2mNdWZZU6T3sSGQPcPXa10twM2dqnNOj99robFLRylxzaDtN2k4sr5YD0P_7FApIrp3RdkyC-_r07qD5t9n6sR9P1ou947RehDFDsZtO8OPcg_gMvnOZkjaQjn1TDhSydmAzR6su37l6-7urhNSmqx8FS_P0YwgQ",
      logoUrl: "",
      description: "A beginner-friendly introduction to analyzing data, creating visualizations, and making data-driven decisions.",
      benefits: "Free Access",
      eligibility: ["Everyone"],
      deadline: "Open",
      value: "Free",
      duration: "2 Days",
      language: "English",
      registrationLink: "#",
      tags: []
    },
    {
      id: 4,
      title: "Women in Tech Grant",
      type: 'Scholarship',
      organization: 'Women Who Code',
      orgDescription: 'Empowering women in technology.',
      location: 'Global • Annual',
      updatedAt: '1 day ago',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0Q2RLR7_xwQRJxajuitmqEa7ZYurrVsUTJeZB6y6QcapcbuzBXLndnnry3Tc6Fg4b4ICx8FOYurgWMnQyykwOX4jRWXW8CIrvstlSUMV3uvRc1S5a_-bg2lpxoBXVzmMZGDvFYW-1a8Xmhj4KaPYaN3UWLcXkx7Ru65q5eXBQUzRdk3oB5GSNQHPIpMH4trN1lzUnYRxov5a_UthFvvOpC_ZtJxvpUGiX4NlI3tpJ6xCqdfgKmGmU6GaiPuXmQwVlOls42PtCMX0',
      logoUrl: 'https://uploads.turbologo.com/uploads/design/preview_image/472636/draw_svg20250109-11786-196169.svg.png',
      description: "Supporting women leaders in Computer Science and Technology.",
      benefits: "$5,000 grant.",
      level: "Undergraduate",
      eligibility: ["Female Undergraduate student in STEM"],
      deadline: "Annual",
      value: "$5,000",
      duration: "1 Year",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 301,
      title: "Global AI Summit 2026",
      type: 'Event',
      organization: 'AI Future Council',
      orgDescription: 'Innovation and ethics in AI.',
      location: 'Paris, France',
      updatedAt: '3 hours ago',
      imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
      logoUrl: '',
      description: "A premier event gathering the world's leading experts to discuss the future of Artificial Intelligence and Machine Learning.",
      benefits: "Networking with experts, Certificate of Attendance",
      eligibility: ["Tech Enthusiasts", "Professionals", "Students"],
      deadline: "Jan 15, 2026",
      value: "€150 (Free for Students)",
      duration: "3 Days",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 5,
      title: "Future Leaders MBA Award",
      type: 'Scholarship',
      organization: 'Melbourne University',
      orgDescription: 'Public research university.',
      location: 'Melbourne, AU',
      updatedAt: '5 hours ago',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1XY49nFFW4D9_bYex5N5cbzifKXqRIFT9JP2Uce2vALmS1fadKIA1BN4ZwEzkSgUXK_Cuxn-tT-ay1oNZblCTnifZBB-wxZNOGZ4dSZLvjmfp8hLD1xGeJd4KDR5Ae_OOieVjki5kn9DeloiDjPN0fQPYrtymd4NQ6XjKh0yARj6SX9pPzMkKYQH9Rq1wRFjkIMtR5TY6WyLrfnkIkMsOxGcSza23QG-jOPBWwwV7Dywt1ppwUmTdGoZxPcvhueL_gvStiqlXFZg',
      logoUrl: 'https://static.vecteezy.com/ti/vecteur-libre/p1/4851944-logo-universitaire-ou-education-logo-concept-vector-illustration-university-logo-design-template-vectoriel.jpg',
      description: "Scholarship for exceptional Business and Management skills.",
      benefits: "Full tuition.",
      level: "Master's Degree",
      eligibility: ["Leadership experience"],
      deadline: "Jan 10, 2025",
      value: "Full Tuition",
      duration: "3 Years",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 6,
      title: "Chevening Scholarship 2025",
      type: 'Scholarship',
      organization: 'UK Government',
      orgDescription: 'Global scholarship programme.',
      location: 'London, UK',
      updatedAt: '1 week ago',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1200px-Flag_of_the_United_Kingdom_%281-2%29.svg.png',
      logoUrl: 'https://t3.ftcdn.net/jpg/06/09/78/22/360_F_609782249_FyRxzIhL8FeQzEPJfHVH2mG6sfBGsbTq.jpg',
      description: "For outstanding emerging leaders to pursue one-year Master's degrees in any field.",
      benefits: "Fully funded.",
      level: "Master's Degree",
      eligibility: ["2 years work experience"],
      deadline: "Nov 07, 2024",
      value: "Fully Funded",
      duration: "1 Year",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 7,
      title: "Global Health Research Grant",
      type: 'Scholarship',
      organization: 'WHO',
      orgDescription: 'World Health Organization.',
      location: 'Berlin, Germany',
      updatedAt: '3 days ago',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/1200px-Flag_of_Germany.svg.png',
      logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXu_D1OOBl_RoPRU6XyeiddDN0EJuOw9lXCw&s',
      description: "For students conducting research in Medical & Health sciences.",
      benefits: "Research funding.",
      level: "PhD / Doctorate",
      eligibility: ["Medical background"],
      deadline: "Oct 30, 2024",
      value: "€20,000",
      duration: "3 Years",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 11,
      title: "Global Undergraduate Exchange Program",
      type: 'Scholarship',
      organization: 'World Learning',
      orgDescription: 'Empowering people.',
      location: 'Washington DC, USA',
      updatedAt: '2 weeks ago',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1XY49nFFW4D9_bYex5N5cbzifKXqRIFT9JP2Uce2vALmS1fadKIA1BN4ZwEzkSgUXK_Cuxn-tT-ay1oNZblCTnifZBB-wxZNOGZ4dSZLvjmfp8hLD1xGeJd4KDR5Ae_OOieVjki5kn9DeloiDjPN0fQPYrtymd4NQ6XjKh0yARj6SX9pPzMkKYQH9Rq1wRFjkIMtR5TY6WyLrfnkIkMsOxGcSza23QG-jOPBWwwV7Dywt1ppwUmTdGoZxPcvhueL_gvStiqlXFZg',
      logoUrl: 'https://static.vecteezy.com/ti/vecteur-libre/p1/4851939-logo-universitaire-ou-education-logo-concept-vector-illustration-university-logo-design-template-vectoriel.jpg',
      description: "A substantial scholarship for one semester of non-degree study.",
      benefits: "Tuition, Travel.",
      level: "Undergraduate",
      eligibility: ["Currently enrolled Undergraduate student"],
      deadline: "Feb 28, 2025",
      value: "Fully Funded",
      duration: "6 Months",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 12,
      title: "Creative Arts Fellowship",
      type: 'Scholarship',
      organization: 'Arts Council',
      orgDescription: 'Supporting artists.',
      location: 'Paris, France',
      updatedAt: '1 day ago',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAC3xWr_MOWHEOrdqWRv3vhTO3aPl59f1zRuijn72JrR9s_HHrpumkRr1z5O6C28FasMCGZrx6uiIdU0yETs_NTAp7IEB5wgs7DS69VorpLpcLhnf5QwKXyGVFE_Kx7Q7NQVvDVOTFQ3j-Y966MfW-w4FoTC08P9R2OoO0F-l206sf09OvXz80oFOSzhDNLiWmJQuuCF8ld0f5AruCeczWoWA4b_dQqawr50ppPS9VJ7RPc2u6gxP8MGG4iSR_CUV8xYmr9pTR-IQzm',
      logoUrl: 'https://thumbs.dreamstime.com/b/conception-de-logo-l-universit%C3%A9-d%C3%A9corative-du-fond-illustration-vecteur-vectorn-conceptuel-182811508.jpg',
      description: "Funding for painters, sculptors and designers in Arts & Humanities.",
      benefits: "Studio space and stipend.",
      level: "Master's Degree",
      eligibility: ["Portfolio required"],
      deadline: "Mar 15, 2025",
      value: "€15,000",
      duration: "1 Year",
      language: "French",
      registrationLink: "#"
    },
    {
      id: 13,
      title: "Silicon Valley AI Scholarship",
      type: 'Scholarship',
      organization: 'Tech Giants',
      location: 'California, USA',
      orgDescription: 'Big Tech.',
      updatedAt: '2 hours ago',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQC7MQsZ9q3WRhvR8Mr5Qav3XoIYZjk8An_UOH55XRIHAc6WlzUsH_QCxVAwexPK30FegBL2WgZqFd-aBOyAllERegfxAvv_H1QmkAipz93UGW21yY6TudutMHjibqKuUPEcTy8hkP8fMTQayJS2bminTJeQBdqycR-0BlgvDtzfpJPmH5F8Uh9tKnD2grxw0EnVvUDy_9iiX1CMDDQRa-FiifWVQU_UrgXHel9tpUmrijtdgO5uZ0s2O03bm6ktK1UwYklCuIPxo',
      logoUrl: 'https://cdn-03.9rayti.com/rsrc/cache/widen_224/uploads/2012/06/logo-ump-universite-mohammed-premier-oujda.png',
      description: "Exclusive funding for Computer Science and Artificial Intelligence students.",
      benefits: "$10,000 award.",
      level: "Undergraduate",
      eligibility: ["CS Major"],
      deadline: "Jan 15, 2026",
      value: "$10,000",
      duration: "1 Year",
      language: "English",
      registrationLink: "#"
    },
    {
      id: 201,
      title: "Full-Stack Web Development Bootcamp",
      type: "Training",
      organization: "Tech Academy",
      orgDescription: "Tech School",
      location: "Online",
      updatedAt: "2 days ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCN52xQPspSJQxszHxWn9lMKKhXAKRUz9Zmq5wZaSTW0TRy9VkDMh1d-5U0L-hLjwlUhQ_c7JJsn-fmkxnex_J_JxbPEG7KkD-xpef8vTNtGKKz2qgv2OwkYm1WWis7ISw1Wgfaz8l5lFblgoTtpZaiWEx58nMxPOM5W9SYETDq2Z3wuQcsncrXs1GKi7SVVaf7_pwucffLc29QPzfko1Pdql_dCLJoFja_m8K5MQ_7-nMN8s3wd688lfzfhp9pLCg_0jP3c5HPzKN1", // Remplacez par une vraie URL si besoin
      logoUrl: "",
      description: "Master React, Node.js, and modern database technologies in this intensive 12-week program designed for career switchers.",
      benefits: "Certified",
      eligibility: ["Beginners"],
      deadline: "Open",
      value: "Paid",
      duration: "12 Weeks",
      tags: ["Featured"],
      language: "English",
      registrationLink: "#"
    },
    {
      id: 202,
      title: "UX/UI Design Fundamentals",
      type: "Training",
      organization: "Creative Institute",
      orgDescription: "Design School",
      location: "Online",
      updatedAt: "1 day ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUPHGvTCjvXzyw0xiX_3GLv3eYTG9cyYXsG28xvJtf7bFVipuUF4RzhbEvQFstTFqt0At6Dy4VKKt0OmbwEohrvwRtYZG7amxJa5Azca3cnsuAyDkcEbAH_XkRlAKpoJKKfM_wn4XDF0VkSs-YkWEG2EqQhzH26UfBdUxczp6gNLNRn8bBR6rJPrT-HSAqMySVGYkeUnxhMjhkl3jtXx72eft16YyeNhFq70w1RHMeCjZj7JUlRO0BfEkXPADZNmkEw-VWI2aCSHu4",
      logoUrl: "",
      description: "Learn user research, prototyping, and interface design principles. Perfect for graphic designers wanting to upskill.",
      benefits: "Portfolio",
      eligibility: ["Designers"],
      deadline: "Open",
      value: "Paid",
      duration: "6 Weeks",
      tags: ["Popular"],
      language: "English",
      registrationLink: "#"
    },
    {
      id: 204,
      title: "Full-Stack Web Development Bootcamp",
      type: "Training",
      organization: "Tech Academy",
      orgDescription: "Coding Bootcamp",
      location: "Online (Live)",
      updatedAt: "1 week ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCN52xQPspSJQxszHxWn9lMKKhXAKRUz9Zmq5wZaSTW0TRy9VkDMh1d-5U0L-hLjwlUhQ_c7JJsn-fmkxnex_J_JxbPEG7KkD-xpef8vTNtGKKz2qgv2OwkYm1WWis7ISw1Wgfaz8l5lFblgoTtpZaiWEx58nMxPOM5W9SYETDq2Z3wuQcsncrXs1GKi7SVVaf7_pwucffLc29QPzfko1Pdql_dCLJoFja_m8K5MQ_7-nMN8s3wd688lfzfhp9pLCg_0jP3c5HPzKN1",
      logoUrl: "",
      description: "Master React, Node.js, and modern database technologies in this intensive 12-week program designed for career switchers.",
      benefits: "Certified Diploma, Career Support",
      eligibility: ["Beginners", "Graduates"],
      deadline: "Jan 30, 2026",
      value: "$1,200",
      duration: "12 Weeks",
      language: "English",
      registrationLink: "#",
      tags: ["Featured"]
    },
    {
      id: 205,
      title: "UX/UI Design Fundamentals",
      type: "Training",
      organization: "Creative Institute",
      orgDescription: "Design School",
      location: "New York, USA",
      updatedAt: "2 days ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUPHGvTCjvXzyw0xiX_3GLv3eYTG9cyYXsG28xvJtf7bFVipuUF4RzhbEvQFstTFqt0At6Dy4VKKt0OmbwEohrvwRtYZG7amxJa5Azca3cnsuAyDkcEbAH_XkRlAKpoJKKfM_wn4XDF0VkSs-YkWEG2EqQhzH26UfBdUxczp6gNLNRn8bBR6rJPrT-HSAqMySVGYkeUnxhMjhkl3jtXx72eft16YyeNhFq70w1RHMeCjZj7JUlRO0BfEkXPADZNmkEw-VWI2aCSHu4",
      logoUrl: "",
      description: "Learn user research, prototyping, and interface design principles. Perfect for graphic designers wanting to upskill.",
      benefits: "Project Portfolio",
      eligibility: ["Designers"],
      deadline: "Feb 15, 2026",
      value: "$299",
      duration: "6 Weeks",
      language: "English",
      registrationLink: "#",
      tags: ["Popular"]
    },
    {
      id: 206,
      title: "Strategic Leadership Masterclass",
      type: "Training",
      organization: "Business School Online",
      orgDescription: "Management Training",
      location: "London, UK",
      updatedAt: "5 days ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDQgcmf_7EvGdLEz9Kc0ZBHKHdI1fj6UH-hWGHzm_XXIDwnaQl0jYRGcvcLrUh12bSCkdRFBH8I8amV6x8wEUGO68VwWI-ZLNrFiLS56mOLtuXgq4Oh1mZeS2r2cJ5IbA0HoOKlbA3YZglaasdlYfV0IuAPeXhaE6DEykhLefNPG_2JbBwepuBxuxvGtpuvRB7P9jfwVeal1-f4euFE7DopwGDVgScci3FM1akCSMTk0lyEZk_8xNR7paexK5kWDmrxIUjXRWvbJsQy",
      logoUrl: "",
      description: "Develop the skills to lead high-performing teams and drive organizational change in today's dynamic market.",
      benefits: "Executive Certificate",
      eligibility: ["Managers", "Team Leads"],
      deadline: "Mar 01, 2026",
      value: "$450",
      duration: "4 Weeks",
      language: "English",
      registrationLink: "#",
      tags: []
    },
    {
      id: 207,
      title: "Digital Marketing Specialist",
      type: "Training",
      organization: "Marketing Pro",
      orgDescription: "Digital Agency",
      location: "Online (Self-paced)",
      updatedAt: "1 day ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDgKozg9dMZGpq86VRo9hc0__csnAZxMu_zk56jZuXhYHJdknsZW-DKJCVk7mANcOZjj1dHFLXexjNOf83Tc4hibXfRmaXBfI2R0ADUFmGqgV6ONXXYhoUkWehGiROB8rKhCERAGuHtlKW2MMHzVh2avuRheTqCJvLcDog0WywrVnd1KZmPNsD0NNkobOjJyJ--OI-y9KMAhce136DzaeU1-s6wtM4tFytV83l0chvmUFI09Z4quXEc-w4G_dcdomIMsj3bWiW5KHwd",
      logoUrl: "",
      description: "Become an expert in SEO, SEM, social media, and email marketing. Get hands-on experience with real projects.",
      benefits: "Free Certification",
      eligibility: ["Everyone"],
      deadline: "Open",
      value: "Free",
      duration: "5 Months",
      language: "English",
      registrationLink: "#",
      tags: []
    },
    {
      id: 208,
      title: "Python for Data Science and AI",
      type: "Training",
      organization: "Tech Academy",
      orgDescription: "Coding School",
      location: "Online",
      updatedAt: "4 days ago",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBAHSkXaTySFGgCVFGgMi9OMD36FEBj7LDFtTsXMEMWOoMgbkNEz3p7HnZmyG_F6fb0d74g8DilAOIHVubxAPekpOZgd4h-LdUSkAkZkp7a_xkro_thUUnOYqYHvh_jcJPsl0QbrtiIwcHVj8ZZKdL3MX-UUz_AomAhkTfJZZuB81orAKqf9zyqGQUuCp9q4gv6ZZMlO7yGQhQH04JTctDG3bFEqNXEC2tZbUPwG0wZWJkWU_ZaaaNRB4gxLX9139SHBNWI9-oe8WX8",
      logoUrl: "",
      description: "Learn Python programming specifically for data analysis and artificial intelligence applications.",
      benefits: "Certified",
      eligibility: ["Students", "Developers"],
      deadline: "Feb 20, 2026",
      value: "$80",
      duration: "8 Weeks",
      language: "English",
      registrationLink: "#",
      tags: ["Popular"]
    },
    {
      id: 302,
      title: "Innovate Morocco Hackathon",
      type: 'Event',
      organization: 'Startup Hub',
      orgDescription: 'Accelerating digital transformation.',
      location: 'Casablanca, Morocco',
      updatedAt: '12 hours ago',
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800',
      logoUrl: '',
      description: "48 hours of intense coding and problem-solving to build solutions for sustainable energy.",
      benefits: "Prize pool of $10,000, Mentorship",
      eligibility: ["Developers", "Designers", "Entrepreneurs"],
      deadline: "Feb 10, 2026",
      value: "Free",
      duration: "2 Days",
      language: "French/English",
      registrationLink: "#"
    },
    // NOUVEL EVENT : Webinar
    {
      id: 303,
      title: "Remote Work & Global Careers",
      type: 'Event',
      organization: 'WorkWorld',
      orgDescription: 'Future of work platform.',
      location: 'Online (Zoom)',
      updatedAt: '1 day ago',
      imageUrl: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=800',
      logoUrl: '',
      description: "Virtual panel discussion about landing high-paying remote jobs and navigating digital nomad visas.",
      benefits: "Resource Kit, Q&A Session",
      eligibility: ["Everyone"],
      deadline: "Open",
      value: "Free",
      duration: "2 Hours",
      language: "English",
      registrationLink: "#"
    },
  ];

  getOpportunities(): Observable<Opportunity[]> {
    return of(this.opportunities);
  }

  getOpportunityById(id: number): Observable<Opportunity | undefined> {
    return of(this.opportunities.find(o => o.id === id));
  }
}
